---
- name: List contents of the home directory
  hosts: webserver
  tasks:
    - name: Run ls command in the home directory
      ansible.builtin.shell: "ls ~"
      register: ls_output

    - name: Display the output of ls command
      debug:
        var: ls_output.stdout
